### ISSUE TITLE
EasyBuild 2.1

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#100]
Current planning: release April 1st 2015

planned changes (more-or-less in order of preference, more changes not listed here can/will be included, only changes that are ready in time will be included):

framework:
* [x] support for `--only-module` (see hpcugent/easybuild-framework#1018) 
  * [x] support for module files in Lua syntax (see hpcugent/easybuild-framework#1060)
* [x] deprecate `log.error`, use `raise EasyBuildError` instead (see hpcugent/easybuild-framework/pull/1218)
* [x] Cray support (see hpcugent/easybuild-framework/pull/1234)
  * [x] add support for `external_modules`, to specify dependencies on modules not produced using EasyBuild (see hpcugent/easybuild-framework/pull/1230)
  * [x] add definitions for toolchains on top of Cray Programming Environment modules  (see hpcugent/easybuild-framework/pull/1234)

easyblocks:
* [x] enhance `PythonPackage` (see hpcugent/easybuild-easyblocks#577)
* [x] fix `$MKLROOT` definition (see hpcugent/easybuild-easyblocks#576)
* various updates to existing easyblocks
* new easyblocks for supporting more software packages

easyconfigs:
* more easyconfigs for software already supported (version updates, other toolchains)
* various easyconfigs for new software
* easyconfig for building a couple of software packages with Cray toolchains, e.g.: CP2K, OpenFOAM, boost, HDF5, WRF, QuantumESPRESSO, NWChem, NAMD, GROMACS, GAMESS-US, Python, ...

postponed:

* deprecate `$EBVAR*` (see hpcugent/easybuild-framework/issues/1219)
* support for GC3Pie backend for `--job` (see hpcugent/easybuild-framework#1008)
* support for `--review-pr` (see hpcugent/easybuild-framework#1142)
* support for Mercurial easyconfigs repository (see hpcugent/easybuild-framework#979)
* support for downloading from SVN repository (see hpcugent/easybuild-framework#1082)
* add support for `--update-module-caches` (see hpcugent/easybuild-framework#1177, depends on https://github.com/TACC/Lmod/pull/58)
* hpcugent/easybuild-easyblocks#475
