### ISSUE TITLE
EasyBuild 2.5.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#170]
List of issues & pull requests that should get handled before EasyBuild v2.5.0 is released (planned to go out before the end of 2015, most likelt mid-December).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### framework

* [x] support for `whatis` easyconfig parameter (@geimer, @boegel)
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1271~~
* [x] rework GCC/GNU toolchains via GCCcore *(1)* (@ocaisa, @geimer, @boegel)
  * framework PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1451~~
  * easyconfigs PR: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2214~~
* [x] support for `--optarch=GENERIC` (@pescobar, @boegel)
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1471~~
* [ ] bug fix for `modpath_extensions_for` function when used with module files in Lua syntax
  * PR: https://github.com/hpcugent/easybuild-framework/pull/1474
* [x] fix `install-EasyBuild-develop.sh` script (@boegel, @pescobar)
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1480~~
* [x] fix `sys_platform` issue in EasyBuild bootstrap (@wpoely86, @boegel)
  * bug: ~~https://github.com/hpcugent/easybuild-framework/issues/1099~~
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1490~~
* [x] support hidden build dependencies
  * bug: ~~https://github.com/hpcugent/easybuild-framework/issues/1368~~
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1503~~

######  easyblocks

* Intel 2016
  * [x] support for 2016 versions of Intel compilers (@DirkdeDraak, @wpoely86, @boegel)
    * PR: ~~https://github.com/hpcugent/easybuild-easyblocks/pull/691~~
  * [x] support for imkl 11.3.1.150 (@jas02, @wpoely86)
    * PR: ~~https://github.com/hpcugent/easybuild-easyblocks/pull/745~~
  * [x] see also ~~https://github.com/hpcugent/easybuild-easyblocks/issues/751~~
  * [x] joint PR: ~~https://github.com/hpcugent/easybuild-easyblocks/pull/756~~
* [ ] fix problems with EasyBuild easyblock (and Python packages in general) picking up Python packages provided by the OS as dependencies (e.g. vsc-base for EasyBuild)

######  easyconfigs

* [x] GCCcore easyconfigs + changes to existing easyconfigs, see *(1)* (@ocaisa, @geimer, @boegel)
  * PR: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2214~~
* [x] `intel/2015.08`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2194~~
* [x] `intel/2016.00`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2209~~
* [x] `intel/2016.01`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2219~~

**Comment by wpoely86** [comment]
I would like to add:
* [ ] patch level enhancements: hpcugent/easybuild-framework#1460  and hpcugent/easybuild-framework#1489

**Comment by boegel** [comment]
@wpoely86: this is not meant to be a complete list, other PRs can certainly be merged too, but I wouldn't consider those two blockers...

**Comment by wpoely86** [comment]
We currently have PR's where `--from-pr` doesn't work and it is fixed by hpcugent/easybuild-framework#1460. So definitely a blocker IMHO.

**Comment by boegel** [comment]
Merge window for EasyBuild v2.5.0 is now *closed*, release is going out shortly.

Unresolved issues mentioned here are moved to v2.6.0, cfr. https://github.com/hpcugent/easybuild/issues/176
