### ISSUE TITLE
EasyBuild 2.6.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#176]
List of issues & pull requests that should get handled before EasyBuild v2.6.0 is released (planned to go out before the end of Jan'16).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### framework

* [x] support for `--new-pr` and `--update-pr`
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1528~~
* [x] support for `--last-log`
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1541~~
* [x] support for user-local modules with hierarchical MNS (`--subdir-user-modules`)
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1472~~

###### easyblocks

* [x] fix problems with EasyBuild easyblock (and Python packages in general) picking up Python packages provided by the OS as dependencies (e.g. vsc-base for EasyBuild)
  * should be fixed by a combination of ~~https://github.com/hpcugent/easybuild-framework/pull/1569~~ and ~~https://github.com/hpcugent/easybuild-easyblocks/pull/813~~ .
* [x] `CrayToolchain` easyblock
  * PR: ~~https://github.com/hpcugent/easybuild-easyblocks/pull/766~~
* [x] support for installing PGI
  * PR: ~~https://github.com/hpcugent/easybuild-easyblocks/pull/658~~ (and ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/1833~~)

###### easyconfigs

* [x] `foss/2016a`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2310~~
   * [x] Python 2.7.11: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2352~~
   * [x] Perl 5.20.3: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2354~~
   * [x] Boost 1.59.0: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2356~~
   * [x] CMake 3.4.1: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2355~~
   * [x] Bison 3.0.4 + M4 1.4.17 + flex 2.5.39/2.6.0: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2353~~
* [x] `intel/2016a`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2311~~
   * [x] Python 2.7.11: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2337~~
   * [x] Perl 5.20.3: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2336~~
   * [x] Boost 1.59.0: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2351~~
   * [x] CMake 3.4.1: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2343~~
   * [x] Bison 3.0.4 + M4 1.4.17 + flex 2.5.39/2.6.0: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2342~~
* [x] Cray toolchain easyconfigs
  * PR: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2222~~

**Comment by boegel** [comment]
unresolved have been moved to 2.7.0, cfr. #192

**Comment by boegel** [comment]
EasyBuild v2.6.0 is released, roadmap for v2.7.0 is at #192
