### ISSUE TITLE
EasyBuild 2.7.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#192]
List of issues & pull requests that should get handled before EasyBuild v2.6.0 is released (planned to go out by mid March'16).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### general

* [ ] auto-generate documentation
  * see https://github.com/hpcugent/easybuild/pull/142, https://github.com/hpcugent/easybuild/pull/143
  * framework support: https://github.com/hpcugent/easybuild-framework/pull/1346
* [x] fix bootstrap script w.r.t. required `setuptools` runtime dep
  * see https://github.com/hpcugent/easybuild-framework/issues/1578
  * PR: https://github.com/hpcugent/easybuild-framework/pull/1655

###### framework

* [x] use `python -O` in `eb`
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1357~~
  * fix/enhance logging format: ~~https://github.com/hpcugent/easybuild-framework/pull/1649~~
* [ ] bug fix for `modpath_extensions_for` function when used with module files in Lua syntax
  * PR: https://github.com/hpcugent/easybuild-framework/pull/1474
* [x] fix problems when Python 3 is the default `python`
  * cfr. https://github.com/hpcugent/easybuild-framework/issues/1410, https://github.com/hpcugent/easybuild-framework/issues/1532
  * PRs:
    * bootstrap script: https://github.com/hpcugent/easybuild-framework/pull/1660
    * https://github.com/hpcugent/easybuild-easyblocks/pull/861
* [x] fix annoying '`already imported`' warnings (https://github.com/hpcugent/easybuild-framework/issues/1588)
 * PR: https://github.com/hpcugent/easybuild-framework/pull/1593 + https://github.com/hpcugent/easybuild-easyblocks/pull/827
* [ ] support for PGI toolchain
  * PR: https://github.com/hpcugent/easybuild-framework/pull/1342
* [x] add support for `--show-config`
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1611~~
* [x] simplify/fix support for `--minimal-toolchains`
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1614~~
  * PR w/ more tests: ~~https://github.com/hpcugent/easybuild-framework/pull/1619~~
  * bug fix PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1622~~
* [x] add support for `--install-github-token` and `--check-github`
  * PR: https://github.com/hpcugent/easybuild-framework/pull/1616
* [x] fix issue with `mpi4py` import done by fancylogger
  * see https://github.com/hpcugent/vsc-base/issues/216
  * fixed in vsc-base: https://github.com/hpcugent/vsc-base/pull/217
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1648~~
* [x] stable Cray support
  * see https://github.com/hpcugent/easybuild-framework/issues/1390

###### easyblocks

* [x] fix `$CPATH` issue in PGI easyblock
  * ~~https://github.com/hpcugent/easybuild-easyblocks/pull/837~~

###### easyconfigs

* [ ] QIIME: https://github.com/hpcugent/easybuild-easyconfigs/pull/1057
* [ ] automated style checks: https://github.com/hpcugent/easybuild-easyconfigs/pull/2376
* [ ] `intel/2016.02`: https://github.com/hpcugent/easybuild-easyconfigs/pull/2523
  * requires `GCC/5.3.0-2.26`: https://github.com/hpcugent/easybuild-easyconfigs/pull/2524
  * [x] `intel/2016.02-GCC-4.9` ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2620~~

**Comment by boegel** [comment]
EasyBuild v2.7.0 is released, unresolved issues/features have been transferred to EasyBuild v2.8.0, cfr. #209
