### ISSUE TITLE
EasyBuild v2.8.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#209]
List of issues & pull requests that should get handled before EasyBuild v2.8.0 is released (planned to go out by mid May'16).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### general

* [ ] auto-generate documentation
  * see https://github.com/hpcugent/easybuild/pull/142, https://github.com/hpcugent/easybuild/pull/143
  * framework support: https://github.com/hpcugent/easybuild-framework/pull/1346

###### framework

* [ ] bug fix for `modpath_extensions_for` function when used with module files in Lua syntax
  * PR: https://github.com/hpcugent/easybuild-framework/pull/1474
* [x] support for PGI toolchain, cfr. ~~https://github.com/hpcugent/easybuild/issues/211~~
* [x] fix issue with too many `module use` calls resulting in lots of overhead
  * ~~https://github.com/hpcugent/easybuild-framework/issues/1661~~
  * PR: ~~https://github.com/hpcugent/easybuild-framework/pull/1735~~
  * see stats in https://github.com/hpcugent/easybuild-framework/pull/946#issuecomment-203850217
  * switch to native Python module with Lmod?
```python
import os, sys
sys.path.insert(0, '%s/../init/' % (os.getenv('LMOD_DIR')))
from env_modules_python import module
module('avail')
```

###### easyblocks

* 

###### easyconfigs

* [ ] QIIME: https://github.com/hpcugent/easybuild-easyconfigs/pull/1057
* [ ] automated style checks: https://github.com/hpcugent/easybuild-easyconfigs/pull/2376
* [x] `intel/2016.02`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2523~~
  * requires `GCC/5.3.0-2.26`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2524~~

**Comment by boegel** [comment]
remaining open issues transferred to v2.9.0... #219

**Comment by boegel** [comment]
rien-ne-va-plus for EasyBuild v2.8.0, cfr. release notes @ https://github.com/hpcugent/easybuild-framework/pull/1765, https://github.com/hpcugent/easybuild-easyblocks/pull/922 and https://github.com/hpcugent/easybuild-easyconfigs/pull/3060
