### ISSUE TITLE
PGI support (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#211]
**framework**

* [x] support for PGI as compiler toolchain (~~https://github.com/hpcugent/easybuild-framework/pull/1342~~)
* [x] support use of PGI with Intel MKL/FFTW (~~https://github.com/hpcugent/easybuild-framework/pull/1664~~)
* [x] `pomkl` toolchain definition (~~https://github.com/hpcugent/easybuild-framework/pull/1724~~)
* [x] support for CrayPGI toolchain (~~https://github.com/hpcugent/easybuild-framework/issues/1729~~)

**easyblocks**

* [x] add PGI support in Intel MKL easyblock (~~https://github.com/hpcugent/easybuild-easyblocks/pull/866~~)
* [x] make PGI easyblock aware of `numactl` (~~https://github.com/hpcugent/easybuild-easyblocks/pull/888~~)

**easyconfigs**

* easyconfig PRs for PGI-based toolchains + HPL as test case
  * [x] PGI 16.3: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2879~~
  * [x] `pompi`: ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2899~~
  * [x] `pomkl`: ~~https://github.com/hpcugent/easybuild-easyconfigs/issues/2900~~
  * [x] `CrayPGI` ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/2927~~

**Comment by boegel** [comment]
cc @ocaisa, @damianam, @bartoldeman, @jgphpc

**Comment by boegel** [comment]
all PRs merged, so closing this...

full PGI support included in the upcoming EasyBuild v2.8.0 \o/
