### ISSUE TITLE
EasyBuild v2.9.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#219]
List of issues & pull requests that should get handled before EasyBuild v2.9.0 is released (planned to go out by end June'16).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### general

* [x] auto-generate documentation
  * see ~~https://github.com/hpcugent/easybuild/pull/142, https://github.com/hpcugent/easybuild/pull/143~~
  * framework support: ~~https://github.com/hpcugent/easybuild-framework/pull/1346~~
* [ ] deprecate old/unused toolchains
  * see https://github.com/hpcugent/easybuild/wiki/Deprecated-toolchains

###### framework

* [x] support for `hidden` easyconfig parameter
  * ~~https://github.com/hpcugent/easybuild-framework/pull/1837~~
* [x] support for hiding toolchains
  * ~~https://github.com/hpcugent/easybuild-framework/pull/1683~~
* [x] support for using `ccache` and `f90cache`
  * ~~https://github.com/hpcugent/easybuild-framework/pull/1844~~
* [ ] enhancements to GitHub integration
  * see https://github.com/hpcugent/easybuild-framework/issues/1674
  * `--new-pr` and `--update-pr` no longer experimental?
* [ ] (experimental) support for RPATH linking
* [ ] support for `devel` logging
  * https://github.com/hpcugent/easybuild-framework/pull/1815
* [x] support for `--list-software`
  * ~~https://github.com/hpcugent/easybuild-framework/pull/1883~~

###### easyblocks

* [x] easyblock to support installing X11 stack behind a single module
  * see ~~https://github.com/hpcugent/easybuild-easyblocks/pull/980~~ and https://github.com/hpcugent/easybuild-easyconfigs/pull/3440

###### easyconfigs

* [ ] archive easyconfigs for deprecated toolchains
* [ ] QIIME: https://github.com/hpcugent/easybuild-easyconfigs/pull/1057
* [ ] automated style checks: https://github.com/hpcugent/easybuild-easyconfigs/pull/2376

**Comment by boegel** [comment]
EasyBuild v2.9.0 is now released, remaining work to be done transferred to next release: #255
