### ISSUE TITLE
EasyBuild v3.0.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#255]
List of issues & pull requests that should get handled before EasyBuild v3.0.0 is released (planned to go out by mid November'16).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended
###### framework

**backward incompatible changes**
- [x] make robot aware of archived easyconfigs (`--consider-archived-easyconfigs`)
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1972~~
- [x] let robot consider subtoolchains, even without `--minimal-toolchains`
  - `--minimal-toolchains` should only reverse the _order_ in which toolchains are considered
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1973~~
- [x] change default configuration
  - Lmod as modules tool + Lua as modules syntax
  - enable `--minimal-toolchains` by default (?) => no, not for now
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1985~~
- [x] get rid of currently deprecated functionality
  - `log.error` should no longer raise
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1978~~

**new features**
- [x] **support for RPATH linking**
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1942~~
- [x] support for `devel` logging
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1815~~

**other**
- [x] enhancements to GitHub integration
  - see https://github.com/hpcugent/easybuild-framework/issues/1674
  - `--new-pr` and `--update-pr` no longer experimental?
  - ~~https://github.com/hpcugent/easybuild-framework/pull/1979~~

###### easyblocks

- [x] let `GCC` give `lib` subdirs preference over `lib64` dirs
  - ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1030~~
- [x] `Conda` easyblock
  - https://github.com/hpcugent/easybuild-easyblocks/pull/950
- [x] make easyblocks aware of `--rpath` where needed
  - ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1031~~

###### easyconfigs
- [x] archive easyconfigs for deprecated toolchains
  - see https://github.com/hpcugent/easybuild/wiki/Deprecated-toolchains
  - `iqacml`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3725
  - `iomkl`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3729
  - `intel-para`/`gpsolf`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3728
  - `gmacml`/`gmpolf`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3738
  - `gimkl`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3736
  - `Clang`-based: https://github.com/hpcugent/easybuild-easyconfigs/pull/3735
  - `ictce`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3731
  - `gmvolf`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3737
  - `goolfc`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3730
  - `goolf`/`gompi`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3732
  - `goalf`: https://github.com/hpcugent/easybuild-easyconfigs/pull/3733

**Comment by boegel** [comment]
update: moved some stuff to the roadmap for EasyBuild v3.1.0, see #268
