### ISSUE TITLE
EasyBuild v3.1.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#268]
List of issues & pull requests that should get handled before EasyBuild v3.1.0 is released (planned to go out by mid Jan'17).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### framework

- [ ] replace `dummy` toolchain by `system` toolchain (deprecate `dummy`)
  -  see https://github.com/hpcugent/easybuild-framework/issues/1181
  - WIP PR https://github.com/hpcugent/easybuild-framework/pull/1233
- [ ] better error reporting
  - include traceback in log for `EasyBuildError`
  - catch all other errors, instruct to open an issue in framework repo or contact mailing list?
- [ ] more user-friendly default behaviour of robot
  - more helpful error message is dependencies could not be resolved, mention `--robot`
  - maybe even try to resolve deps even if `--robot` was not enabled, and mention that deps _could_ be resolved?
  - https://github.com/hpcugent/easybuild-framework/issues/1015

###### easyblocks

- [x] make FFTW of architecture to selectively enable `--enable-avx --enable-avx2`?
  - see ~~https://github.com/hpcugent/easybuild-easyblocks/pull/1083~~
- [ ] include statement to set up build environment in generated toolchain modules?
  - requires tweaking of `make_module_extra` in `Toolchain` generic easyblock
  - WIP PR at https://github.com/hpcugent/easybuild-easyblocks/pull/1052

###### easyconfigs

- [ ] QIIME: https://github.com/hpcugent/easybuild-easyconfigs/pull/1057
  - stop gap approach via `conda` got merged at ~~https://github.com/hpcugent/easybuild-easyconfigs/pull/3868~~
- [ ] automated style checks: https://github.com/hpcugent/easybuild-easyconfigs/pull/2376

**Comment by boegel** [comment]
EasyBuild v3.1.0 is available now; most of the stuff that was on the roadmap here didn't make it in, so I shifted it to v3.2.0 (cfr. #302)...
