### ISSUE TITLE
EasyBuild 3.2.0 (roadmap)

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild#302]
List of issues & pull requests that should get handled before EasyBuild v3.2.0 is released (planned to go out by mid March '17).

**note**: the plan is to limit things to 5 'major' changes that are still "in flight" (to help with focusing things); as the mentioned pull requests get merged, this list can be updated/extended

###### framework

- [ ] replace `dummy` toolchain by `system` toolchain (deprecate `dummy`)
  -  see https://github.com/hpcugent/easybuild-framework/issues/1181
  - WIP PR https://github.com/hpcugent/easybuild-framework/pull/1233
- [ ] better error reporting
  - include traceback in log for `EasyBuildError`
  - catch all other errors, instruct to open an issue in framework repo or contact mailing list?
- [ ] more user-friendly default behaviour of robot
  - more helpful error message is dependencies could not be resolved, mention `--robot`
  - maybe even try to resolve deps even if `--robot` was not enabled, and mention that deps _could_ be resolved?
  - https://github.com/hpcugent/easybuild-framework/issues/1015

###### easyblocks

- [ ] include statement to set up build environment in generated toolchain modules?
  - requires tweaking of `make_module_extra` in `Toolchain` generic easyblock
  - WIP PR at https://github.com/hpcugent/easybuild-easyblocks/pull/1052

###### easyconfigs

- [ ] 'proper' support for QIIME: https://github.com/hpcugent/easybuild-easyconfigs/pull/1057
- [ ] automated style checks: https://github.com/hpcugent/easybuild-easyconfigs/pull/2506

**Comment by wpoely86** [comment]
@boegel you want hpcugent/easybuild-easyconfigs#2506 for the style checks

**Comment by boegel** [comment]
clearly setting targets for a release isn't working out, as priorities are shifting all the time

To see what actually made it into v3.2.0, see http://easybuild.readthedocs.io/en/latest/Release_notes.html
